# Numbers with underscores, please.
Style/NumericLiterals:
  Enabled: true

# Allow more complex if statements ( if { if { if {} } })
Metrics/AbcSize:
  Max: 30

# Allow slightly longer classes
Metrics/ClassLength:
  CountComments: false
  Max: 150

# Allow sightly longer lines
Metrics/LineLength:
  Max: 120

# Allow slightly longer methods
Metrics/MethodLength:
  Max: 50

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

# Rocketships!
HashSyntax:
  EnforcedStyle: hash_rockets

# Allow use of "fail", "raise"
Style/SignalException:
  Enabled: false

# Allow "not" as well as "!"
Style/Not:
  Enabled: false
